var menu_items = [  
    {item: "goals_per90", display: "Goals"}, 
    {item: "assists_per90", display: "Assists"}, 
    {item: "non-penalty_goals_per90", display: "Non-Penalty Goals"}, 
    {item: "penalty_kicks_made_per90", display: "Penalty Kicks Made"}, 
    {item: "penalty_kicks_attempted_per90", display: "Penalty Kicks Attempted"}, 
    {item: "yellow_cards_per90", display: "Yellow Cards"}, 
    {item: "red_cards_per90", display: "Red Cards"}, 
    {item: "xg_per90", display: "Expected Goals"}, 
    {item: "npxg_per90", display: "Non-Pen Expected Goals"}, 
    {item: "xa_per90", display: "Expected Assists"}, 
    {item: "npxg+xa_per90", display: "Npxg+Xa"}, 
    {item: "shots_total_per90", display: "Shots Total"}, 
    {item: "shots_on_target_per90", display: "Shots On Target"}, 
    // {item: "shots_on_target_%_per90", display: "Shots On Target %"}, 
    {item: "goals/shot_per90", display: "Goals/Shot"}, 
    {item: "goals/shot_on_target_per90", display: "Goals/Shot On Target"}, 
    {item: "average_shot_distance_per90", display: "Average Shot Distance"}, 
    {item: "shots_from_free_kicks_per90", display: "Shots From Free Kicks"}, 
    {item: "npxg/sh_per90", display: "Npxg/Sh"}, 
    {item: "goals_-_xg_per90", display: "Goals - Xg"}, 
    {item: "non-penalty_goals_-_npxg_per90", display: "Non-Penalty Goals - Npxg"}, 
    {item: "passes_completed_per90", display: "Passes Completed"}, 
    {item: "passes_attempted_per90", display: "Passes Attempted"}, 
    // {item: "pass_completion_%_per90", display: "Pass Completion %"}, 
    {item: "total_passing_distance_per90", display: "Total Passing Distance"}, 
    {item: "progressive_passing_distance_per90", display: "Progressive Passing Distance"}, 
    {item: "passes_completed_(short)_per90", display: "Passes Completed (Short)"}, 
    {item: "passes_attempted_(short)_per90", display: "Passes Attempted (Short)"}, 
    // {item: "pass_completion_%_(short)_per90", display: "Pass Completion % (Short)"}, 
    {item: "passes_completed_(medium)_per90", display: "Passes Completed (Medium)"}, 
    {item: "passes_attempted_(medium)_per90", display: "Passes Attempted (Medium)"}, 
    // {item: "pass_completion_%_(medium)_per90", display: "Pass Completion % (Medium)"}, 
    {item: "passes_completed_(long)_per90", display: "Passes Completed (Long)"}, 
    {item: "passes_attempted_(long)_per90", display: "Passes Attempted (Long)"}, 
    // {item: "pass_completion_%_(long)_per90", display: "Pass Completion % (Long)"}, 
    {item: "key_passes_per90", display: "Key Passes"}, 
    {item: "passes_into_final_third_per90", display: "Passes Into Final Third"}, 
    {item: "passes_into_penalty_area_per90", display: "Passes Into Penalty Area"}, 
    {item: "crosses_into_penalty_area_per90", display: "Crosses Into Penalty Area"}, 
    {item: "progressive_passes_per90", display: "Progressive Passes"}, 
    {item: "live-ball_passes_per90", display: "Live-Ball Passes"}, 
    {item: "dead-ball_passes_per90", display: "Dead-Ball Passes"},
    {item: "passes_from_free_kicks_per90", display: "Passes From Free Kicks"}, 
    {item: "through_balls_per90", display: "Through Balls"}, 
    {item: "passes_under_pressure_per90", display: "Passes Under Pressure"}, 
    {item: "switches_per90", display: "Switches"}, 
    {item: "crosses_per90", display: "Crosses"}, 
    {item: "corner_kicks_per90", display: "Corner Kicks"}, 
    {item: "inswinging_corner_kicks_per90", display: "Inswinging Corner Kicks"}, 
    {item: "outswinging_corner_kicks_per90", display: "Outswinging Corner Kicks"}, 
    {item: "straight_corner_kicks_per90", display: "Straight Corner Kicks"}, 
    {item: "ground_passes_per90", display: "Ground Passes"}, 
    {item: "low_passes_per90", display: "Low Passes"}, 
    {item: "high_passes_per90", display: "High Passes"}, 
    {item: "passes_attempted_(left)_per90", display: "Passes Attempted (Left)"}, 
    {item: "passes_attempted_(right)_per90", display: "Passes Attempted (Right)"}, 
    {item: "passes_attempted_(head)_per90", display: "Passes Attempted (Head)"}, 
    {item: "throw-ins_taken_per90", display: "Throw-Ins Taken"}, 
    {item: "passes_attempted_(other)_per90", display: "Passes Attempted (Other)"}, 
    {item: "passes_offside_per90", display: "Passes Offside"}, 
    {item: "passes_out_of_bounds_per90", display: "Passes Out Of Bounds"}, 
    {item: "passes_intercepted_per90", display: "Passes Intercepted"}, 
    {item: "passes_blocked_per90", display: "Passes Blocked"}, 
    {item: "shot-creating_actions_per90", display: "Shot-Creating Actions"}, 
    {item: "sca_(passlive)_per90", display: "Sca (Passlive)"}, 
    {item: "sca_(passdead)_per90", display: "Sca (Passdead)"}, 
    {item: "sca_(drib)_per90", display: "Sca (Drib)"}, 
    {item: "sca_(sh)_per90", display: "Sca (Sh)"}, 
    {item: "sca_(fld)_per90", display: "Sca (Fld)"}, 
    {item: "sca_(def)_per90", display: "Sca (Def)"}, 
    {item: "goal-creating_actions_per90", display: "Goal-Creating Actions"}, 
    {item: "gca_(passlive)_per90", display: "Gca (Passlive)"}, 
    {item: "gca_(passdead)_per90", display: "Gca (Passdead)"}, 
    {item: "gca_(drib)_per90", display: "Gca (Drib)"}, 
    {item: "gca_(sh)_per90", display: "Gca (Sh)"}, 
    {item: "gca_(fld)_per90", display: "Gca (Fld)"}, 
    {item: "gca_(def)_per90", display: "Gca (Def)"}, 
    {item: "tackles_per90", display: "Tackles"}, 
    {item: "tackles_won_per90", display: "Tackles Won"}, 
    {item: "tackles_(def_3rd)_per90", display: "Tackles (Def 3Rd)"}, 
    {item: "tackles_(mid_3rd)_per90", display: "Tackles (Mid 3Rd)"}, 
    {item: "tackles_(att_3rd)_per90", display: "Tackles (Att 3Rd)"}, 
    {item: "dribblers_tackled_per90", display: "Dribblers Tackled"}, 
    {item: "dribbles_contested_per90", display: "Dribbles Contested"}, 
    // {item: "%_of_dribblers_tackled_per90", display: "% Of Dribblers Tackled"}, 
    {item: "dribbled_past_per90", display: "Dribbled Past"}, 
    {item: "pressures_per90", display: "Pressures"}, 
    {item: "successful_pressures_per90", display: "Successful Pressures"}, 
    // {item: "successful_pressure_%_per90", display: "Successful Pressure %"}, 
    {item: "pressures_(def_3rd)_per90", display: "Pressures (Def 3Rd)"}, 
    {item: "pressures_(mid_3rd)_per90", display: "Pressures (Mid 3Rd)"}, 
    {item: "pressures_(att_3rd)_per90", display: "Pressures (Att 3Rd)"}, 
    {item: "blocks_per90", display: "Blocks"}, 
    {item: "shots_blocked_per90", display: "Shots Blocked"}, 
    {item: "shots_saved_per90", display: "Shots Saved"}, 
    {item: "interceptions_per90", display: "Interceptions"}, 
    {item: "tkl+int_per90", display: "Tkl+Int"}, 
    {item: "clearances_per90", display: "Clearances"}, 
    {item: "errors_per90", display: "Errors"}, 
    {item: "touches_per90", display: "Touches"}, 
    {item: "touches_(def_pen)_per90", display: "Touches (Def Pen)"}, 
    {item: "touches_(def_3rd)_per90", display: "Touches (Def 3Rd)"}, 
    {item: "touches_(mid_3rd)_per90", display: "Touches (Mid 3Rd)"}, 
    {item: "touches_(att_3rd)_per90", display: "Touches (Att 3Rd)"}, 
    {item: "touches_(att_pen)_per90", display: "Touches (Att Pen)"}, 
    {item: "touches_(live-ball)_per90", display: "Touches (Live-Ball)"}, 
    {item: "dribbles_completed_per90", display: "Dribbles Completed"}, 
    {item: "dribbles_attempted_per90", display: "Dribbles Attempted"}, 
    // {item: "successful_dribble_%_per90", display: "Successful Dribble %"}, 
    {item: "players_dribbled_past_per90", display: "Players Dribbled Past"}, 
    {item: "nutmegs_per90", display: "Nutmegs"}, 
    {item: "carries_per90", display: "Carries"}, 
    {item: "total_carrying_distance_per90", display: "Total Carrying Distance"}, 
    {item: "progressive_carrying_distance_per90", display: "Progressive Carrying Distance"}, 
    {item: "progressive_carries_per90", display: "Progressive Carries"}, 
    {item: "carries_into_final_third_per90", display: "Carries Into Final Third"}, 
    {item: "carries_into_penalty_area_per90", display: "Carries Into Penalty Area"}, 
    {item: "miscontrols_per90", display: "Miscontrols"}, 
    {item: "dispossessed_per90", display: "Dispossessed"}, 
    {item: "pass_targets_per90", display: "Pass Targets"},
    {item: "passes_received_per90", display: "Passes Received"}, 
    // {item: "passes_received_%_per90", display: "Passes Received %"}, 
    {item: "progressive_passes_rec_per90", display: "Progressive Passes Rec"}, 
    {item: "second_yellow_card_per90", display: "Second Yellow Card"}, 
    {item: "fouls_committed_per90", display: "Fouls Committed"}, 
    {item: "fouls_drawn_per90", display: "Fouls Drawn"}, 
    {item: "offsides_per90", display: "Offsides"}, 
    {item: "penalty_kicks_won_per90", display: "Penalty Kicks Won"}, 
    {item: "penalty_kicks_conceded_per90", display: "Penalty Kicks Conceded"}, 
    {item: "own_goals_per90", display: "Own Goals"}, 
    {item: "ball_recoveries_per90", display: "Ball Recoveries"}, 
    {item: "aerials_won_per90", display: "Aerials Won"}, 
    {item: "aerials_lost_per90", display: "Aerials Lost"}
]


var positions= [
    { item: "att", display: "Att" },
    { item: "mid", display: "Mid" },
    { item: "full", display: "Full" },
    { item: "def", display: "Def" },
    { item: "all", display: "All" }
];

var leagues= [
    { item: "england", display: "EPL" },
    { item: "italy", display: "Serie A" },
    { item: "spain", display: "La Liga" },
    { item: "germany", display: "Bundesliga" },
    { item: "france", display: "Ligue 1" }
];

export { menu_items, positions, leagues };